//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOAL
    {
        public int goalID { get; set; }
        public string goalName { get; set; }
        public Nullable<int> goalValue { get; set; }
        public Nullable<System.DateTime> FYstart { get; set; }
        public Nullable<System.DateTime> FYend { get; set; }
        public string subcategory { get; set; }
        public string category { get; set; }
        public string workstream { get; set; }
        public string team { get; set; }
    }
}
