//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM_WORKSTREAM
    {
        public int team_workstreamID { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<int> workstreamID { get; set; }
    
        public virtual TEAM TEAM { get; set; }
        public virtual WORKSTREAM WORKSTREAM { get; set; }
    }
}
