//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKSTREAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKSTREAM()
        {
            this.CONNECTIONs = new HashSet<CONNECTION>();
        }
    
        public int workstreamID { get; set; }
        public string workstreamName { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> subcategoryID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONNECTION> CONNECTIONs { get; set; }
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
        public virtual TEAM TEAM { get; set; }
    }
}
